### ISSUE TITLE
feedback : menu html sur une ligne 

### ISSUE THREAD

**Issue by westindev-lbr** [ManonTgr/site-restaurant#1]
<img width="436" alt="Capture d’écran 2024-01-23 à 23 27 41" src="https://github.com/ManonTgr/site-restaurant/assets/102034752/64f1363f-311f-42aa-a305-3e6b2ea1fd67">

* style.css : 
```css
.menu {
    display: flex;
    list-style: none;
}

.menu li {
    margin: 20px;
}
```

* menu.html : 
```html
<nav>
      <div class="profil">
          <ul class="menu">
              <li><a href="#">Services</a></li>
              <li><a href="#">Menu</a></li>
              <li><a href="#">Reservation</a></li>
              <li><a href="#">Contact</a></li>
          </ul>
      </div>
</nav>
```
